### ISSUE TITLE
com.google.unity.ads.UnityAdLoaderListener

### ISSUE THREAD

**Issue by Hamed1984** [tapsellorg/TapsellPlusSDK-UnityPlugin#1]
سلام
تبلیغات جایزه ای نشون میده اما بنری نشون نمیده و این خطا رو میده لطفاً راهنمایی کنید
این فایل هم googlemobileads-unity.aar در پروژه هست اما بازم این خطا رو میده
Exception
     condition : AndroidJavaException: java.lang.ClassNotFoundException: com.google.unity.ads.UnityAdLoaderListener
       stackTrace : java.lang.ClassNotFoundException: com.google.unity.ads.UnityAdLoaderListener
java.lang.Class.classForName(Native Method)
java.lang.Class.forName(Class.java:454)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.access$500(Unknown Source:0)
com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:126)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loopOnce(Looper.java:211)
android.os.Looper.loop(Looper.java:300)

**Comment by MortezaNedaei** [comment]
سلام پکیج مربوط به تبلیغات نیتیو بنر ادموب را هم باید اضافه کنید
https://dl.google.com/googleadmobadssdk/GoogleMobileAds-native.unitypackage

**Comment by Hamed1984** [comment]
این پکیج داخل خود پکیج تپسل هست و در پروژه وجود دارد.

**Comment by MortezaNedaei** [comment]
- داخل پکیج تپسل، به دلیل کاهش حجم کتابخانه، یک نسخه کم‌حجم از این پکیج‌های ادموب استفاده شده. 
- شما باید مجددا خودتون این دو پکیج رو دانلود و اضافه کنید به پروژه.
- در نظر داشته باشید که داخل این دو پکیج، دو تا فایل با فرمت `aar` وجود داره که حتما باید موقع ایمپورت به پروژه اضافه کنید. احتمالا این دو فایل به پلاگین های شما اضافه نشدن.

https://github.com/googleads/googleads-mobile-unity/releases/download/v8.3.0/GoogleMobileAds-v8.3.0.unitypackage

https://dl.google.com/googleadmobadssdk/GoogleMobileAds-native.unitypackage

**Comment by Hamed1984** [comment]
درست شد ممنون. ولی ای کاش این نکات و توی داکیومنت ها بنویسید تا بعضی ها مثل من چند روز معطل این قضیه نشن.

**Comment by MortezaNedaei** [comment]
بسیار عالی، حتما
