### ISSUE TITLE
Could not resolve com.mbridge.msdk.oversea:interstitialvideo:16.4.41.

### ISSUE THREAD

**Issue by miladtion** [tapsellorg/TapsellPlusSDK-UnityPlugin#2]
سلام من  به ارور زیر موقع بیلد بر میخورم. ورژن یونیتی 2022.3.22f1

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':launcher:checkReleaseDuplicateClasses'.
> Could not resolve all files for configuration ':launcher:releaseRuntimeClasspath'.
   > Could not find com.mbridge.msdk.oversea:interstitialvideo:16.4.41.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mbridge/msdk/oversea/interstitialvideo/16.4.41/interstitialvideo-16.4.41.pom
       - https://repo.maven.apache.org/maven2/com/mbridge/msdk/oversea/interstitialvideo/16.4.41/interstitialvideo-16.4.41.pom
       - https://maven.google.com/com/mbridge/msdk/oversea/interstitialvideo/16.4.41/interstitialvideo-16.4.41.pom
       - file:/Users/milad/.m2/repository/com/mbridge/msdk/oversea/interstitialvideo/16.4.41/interstitialvideo-16.4.41.pom
       - file:/Users/milad/TapsellTest 2022/Library/Bee/Android/Prj/Mono2x/Gradle/unityLibrary/libs/interstitialvideo-16.4.41.jar
       - file:/Users/milad/TapsellTest 2022/Library/Bee/Android/Prj/Mono2x/Gradle/unityLibrary/libs/interstitialvideo.jar
     Required by:
         project :launcher > project :unityLibrary
   > Could not find com.mbridge.msdk.oversea:mbbanner:16.4.41.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mbridge/msdk/oversea/mbbanner/16.4.41/mbbanner-16.4.41.pom
       - https://repo.maven.apache.org/maven2/com/mbridge/msdk/oversea/mbbanner/16.4.41/mbbanner-16.4.41.pom
       - https://maven.google.com/com/mbridge/msdk/oversea/mbbanner/16.4.41/mbbanner-16.4.41.pom
       - file:/Users/milad/.m2/repository/com/mbridge/msdk/oversea/mbbanner/16.4.41/mbbanner-16.4.41.pom
       - file:/Users/milad/TapsellTest 2022/Library/Bee/Android/Prj/Mono2x/Gradle/unityLibrary/libs/mbbanner-16.4.41.jar
       - file:/Users/milad/TapsellTest 2022/Library/Bee/Android/Prj/Mono2x/Gradle/unityLibrary/libs/mbbanner.jar
     Required by:
         project :launcher > project :unityLibrary
   > Could not find com.mbridge.msdk.oversea:mbjscommon:16.4.41.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mbridge/msdk/oversea/mbjscommon/16.4.41/mbjscommon-16.4.41.pom
       - https://repo.maven.apache.org/maven2/com/mbridge/msdk/oversea/mbjscommon/16.4.41/mbjscommon-16.4.41.pom
       - https://maven.google.com/com/mbridge/msdk/oversea/mbjscommon/16.4.41/mbjscommon-16.4.41.pom
       - file:/Users/milad/.m2/repository/com/mbridge/msdk/oversea/mbjscommon/16.4.41/mbjscommon-16.4.41.pom
       - file:/Users/milad/TapsellTest 2022/Library/Bee/Android/Prj/Mono2x/Gradle/unityLibrary/libs/mbjscommon-16.4.41.jar
       - file:/Users/milad/TapsellTest 2022/Library/Bee/Android/Prj/Mono2x/Gradle/unityLibrary/libs/mbjscommon.jar
     Required by:
         project :launcher > project :unityLibrary
   > Could not find com.mbridge.msdk.oversea:playercommon:16.4.41.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mbridge/msdk/oversea/playercommon/16.4.41/playercommon-16.4.41.pom
       - https://repo.maven.apache.org/maven2/com/mbridge/msdk/oversea/playercommon/16.4.41/playercommon-16.4.41.pom
       - https://maven.google.com/com/mbridge/msdk/oversea/playercommon/16.4.41/playercommon-16.4.41.pom
       - file:/Users/milad/.m2/repository/com/mbridge/msdk/oversea/playercommon/16.4.41/playercommon-16.4.41.pom
       - file:/Users/milad/TapsellTest 2022/Library/Bee/Android/Prj/Mono2x/Gradle/unityLibrary/libs/playercommon-16.4.41.jar
       - file:/Users/milad/TapsellTest 2022/Library/Bee/Android/Prj/Mono2x/Gradle/unityLibrary/libs/playercommon.jar
     Required by:
         project :launcher > project :unityLibrary
   > Could not find com.mbridge.msdk.oversea:reward:16.4.41.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mbridge/msdk/oversea/reward/16.4.41/reward-16.4.41.pom
       - https://repo.maven.apache.org/maven2/com/mbridge/msdk/oversea/reward/16.4.41/reward-16.4.41.pom
       - https://maven.google.com/com/mbridge/msdk/oversea/reward/16.4.41/reward-16.4.41.pom
       - file:/Users/milad/.m2/repository/com/mbridge/msdk/oversea/reward/16.4.41/reward-16.4.41.pom
       - file:/Users/milad/TapsellTest 2022/Library/Bee/Android/Prj/Mono2x/Gradle/unityLibrary/libs/reward-16.4.41.jar
       - file:/Users/milad/TapsellTest 2022/Library/Bee/Android/Prj/Mono2x/Gradle/unityLibrary/libs/reward.jar
     Required by:
         project :launcher > project :unityLibrary
   > Could not find com.mbridge.msdk.oversea:same:16.4.41.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mbridge/msdk/oversea/same/16.4.41/same-16.4.41.pom
       - https://repo.maven.apache.org/maven2/com/mbridge/msdk/oversea/same/16.4.41/same-16.4.41.pom
       - https://maven.google.com/com/mbridge/msdk/oversea/same/16.4.41/same-16.4.41.pom
       - file:/Users/milad/.m2/repository/com/mbridge/msdk/oversea/same/16.4.41/same-16.4.41.pom
       - file:/Users/milad/TapsellTest 2022/Library/Bee/Android/Prj/Mono2x/Gradle/unityLibrary/libs/same-16.4.41.jar
       - file:/Users/milad/TapsellTest 2022/Library/Bee/Android/Prj/Mono2x/Gradle/unityLibrary/libs/same.jar
     Required by:
         project :launcher > project :unityLibrary
   > Could not find com.mbridge.msdk.oversea:videocommon:16.4.41.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mbridge/msdk/oversea/videocommon/16.4.41/videocommon-16.4.41.pom
       - https://repo.maven.apache.org/maven2/com/mbridge/msdk/oversea/videocommon/16.4.41/videocommon-16.4.41.pom
       - https://maven.google.com/com/mbridge/msdk/oversea/videocommon/16.4.41/videocommon-16.4.41.pom
       - file:/Users/milad/.m2/repository/com/mbridge/msdk/oversea/videocommon/16.4.41/videocommon-16.4.41.pom
       - file:/Users/milad/TapsellTest 2022/Library/Bee/Android/Prj/Mono2x/Gradle/unityLibrary/libs/videocommon-16.4.41.jar
       - file:/Users/milad/TapsellTest 2022/Library/Bee/Android/Prj/Mono2x/Gradle/unityLibrary/libs/videocommon.jar
     Required by:
         project :launcher > project :unityLibrary
   > Could not find com.mbridge.msdk.oversea:videojs:16.4.41.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mbridge/msdk/oversea/videojs/16.4.41/videojs-16.4.41.pom
       - https://repo.maven.apache.org/maven2/com/mbridge/msdk/oversea/videojs/16.4.41/videojs-16.4.41.pom
       - https://maven.google.com/com/mbridge/msdk/oversea/videojs/16.4.41/videojs-16.4.41.pom
       - file:/Users/milad/.m2/repository/com/mbridge/msdk/oversea/videojs/16.4.41/videojs-16.4.41.pom
       - file:/Users/milad/TapsellTest 2022/Library/Bee/Android/Prj/Mono2x/Gradle/unityLibrary/libs/videojs-16.4.41.jar
       - file:/Users/milad/TapsellTest 2022/Library/Bee/Android/Prj/Mono2x/Gradle/unityLibrary/libs/videojs.jar
     Required by:
         project :launcher > project :unityLibrary

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':unityLibrary:generateReleaseRFile'.
> Could not resolve all files for configuration ':unityLibrary:releaseCompileClasspath'.
   > Could not find com.mbridge.msdk.oversea:interstitialvideo:16.4.41.
     Required by:
         project :unityLibrary
   > Could not find com.mbridge.msdk.oversea:mbbanner:16.4.41.
     Required by:
         project :unityLibrary
   > Could not find com.mbridge.msdk.oversea:mbjscommon:16.4.41.
     Required by:
         project :unityLibrary
   > Could not find com.mbridge.msdk.oversea:playercommon:16.4.41.
     Required by:
         project :unityLibrary
   > Could not find com.mbridge.msdk.oversea:reward:16.4.41.
     Required by:
         project :unityLibrary
   > Could not find com.mbridge.msdk.oversea:same:16.4.41.
     Required by:
         project :unityLibrary
   > Could not find com.mbridge.msdk.oversea:videocommon:16.4.41.
     Required by:
         project :unityLibrary
   > Could not find com.mbridge.msdk.oversea:videojs:16.4.41.
     Required by:
         project :unityLibrary

**Comment by MortezaNedaei** [comment]
سلام این مشکل مشابه [#32](https://github.com/tapsellorg/TapsellPlusSDK-UnitySample2019/issues/32) هست و به دلیل مشکل در دانلود کتابخانه های مینتگرال اتفاق میوفته که  در [خطاهای رایج](https://docs.tapsell.ir/faq/plus-sdk/unity/#%D9%85%D8%B4%DA%A9%D9%84-%D8%AF%D8%B1-%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-%DA%A9%D8%AA%D8%A7%D8%A8%D8%AE%D8%A7%D9%86%D9%87-%D9%87%D8%A7%DB%8C-mintegral) آورده شده. 

۱- شما میتونید پکیج های مینتگرال رو طبق [این لینک](https://docs.tapsell.ir/faq/plus-sdk/unity/#%D9%85%D8%B4%DA%A9%D9%84-%D8%AF%D8%B1-%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-%DA%A9%D8%AA%D8%A7%D8%A8%D8%AE%D8%A7%D9%86%D9%87-%D9%87%D8%A7%DB%8C-mintegral) به صورت آفلاین به پروژه اضافه کنید. کافیه که پکیج ها رو از لینک زیر دانلود کنید. 
[Download Mintegral-AARs.zip](https://github.com/tapsellorg/TapsellPlusSDK-UnitySample2019/files/14469083/Mintegral-AARs.zip)

۲- در صورتیکه قصد غیر فعال کردن مینتگرال رو دارید، لازمه فایل `TapsellPlusDependencies.xml`  رو باز کرده و کتابخانه های مینتگرال (`com.mbridge.msdk.oversea`) رو غیر فعال کنید.

**Comment by MH2B** [comment]
ورژن فایل هایی که گذاشتین قدیمیه اگر نسخه 16.4.41 رو هم بزارین ممنون میشم 
@MortezaNedaei

**Comment by MortezaNedaei** [comment]
در آینده نسخه جدیدش رو قرار میدیم، ولی فعلا شما نسخه داخل `TapsellPlusDependencies.xml` رو به `16.3.91` دانگرید کنید.
